// <auto-generated />
using System;
using Chess.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.Web.Data.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    partial class ChessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Chess.Web.Data.Entities.GameEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BlackTimeRemainingMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndReason")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncrementSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialFen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InitialTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RematchCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("RematchOfCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WhiteTimeRemainingMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.HasIndex("Status");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Chess.Web.Data.Entities.MoveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BlackTimeRemainingMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenAfter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("San")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uci")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<long?>("WhiteTimeRemainingMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameCode", "Ply")
                        .IsUnique();

                    b.ToTable("Moves", (string)null);
                });

            modelBuilder.Entity("Chess.Web.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameCode", "Color")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Chess.Web.Data.Entities.MoveEntity", b =>
                {
                    b.HasOne("Chess.Web.Data.Entities.GameEntity", null)
                        .WithMany("Moves")
                        .HasForeignKey("GameCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chess.Web.Data.Entities.PlayerEntity", b =>
                {
                    b.HasOne("Chess.Web.Data.Entities.GameEntity", null)
                        .WithMany("Players")
                        .HasForeignKey("GameCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chess.Web.Data.Entities.GameEntity", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
